### ISSUE TITLE
Bug: [TS] No overload matches this call. 

### ISSUE THREAD

**Issue by moshie** [express-validator/express-validator#961]
## Describe the bug

When using as middleware typescript complains about the `ValidationChain` not being assignable to a `RequestHandler`

```
const getCertificateValidation = [
  query('data')
    .not()
    .isEmpty()
    .trim()
    .isBase64()
    .customSanitizer((value) => JSON.parse(Buffer.from(value, 'base64').toString()))
    .isJSON(),
];
```

```ts
routes.get('/investors/certificate', getCertificateValidation, getCertificate);
```

Error in full:
```
No overload matches this call.
  Overload 1 of 3, '(path: PathParams, ...handlers: RequestHandler<null, any, null, SanitisedQueryData>[]): Router', gave the following error.
    Argument of type 'ValidationChain[]' is not assignable to parameter of type 'RequestHandler<null, any, null, SanitisedQueryData>'.
      Type 'ValidationChain[]' provides no match for the signature '(req: Request<null, any, null, SanitisedQueryData>, res: Response<any, number>, next: NextFunction): any'.
  Overload 2 of 3, '(path: PathParams, ...handlers: RequestHandlerParams<Record<string, any> | undefined, any, null, SanitisedQueryData>[]): Router', gave the following error.
    Argument of type '(req: Request<null, null, null, SanitisedQueryData>, res: Response) => Promise<void>' is not assignable to parameter of type 'RequestHandlerParams<Record<string, any> | undefined, any, null, SanitisedQueryData>'.
      Type '(req: Request<null, null, null, SanitisedQueryData>, res: Response) => Promise<void>' is not assignable to type 'RequestHandler<Record<string, any> | undefined, any, null, SanitisedQueryData>'.
        Types of parameters 'req' and 'req' are incompatible.
          Type 'Request<Record<string, any> | undefined, any, null, SanitisedQueryData>' is not assignable to type 'Request<null, null, null, SanitisedQueryData>'.
            Types of property 'params' are incompatible.
              Type 'Record<string, any> | undefined' is not assignable to type 'null'.
                Type 'undefined' is not assignable to type 'null'.
```

## Express-validator version:
 - Version: 6.8.0

**Comment by fedeci** [comment]
Hi, I can not reproduce this error, but I am pretty sure it is caused by the `getCertificate` middleware.

This is the code used to test it:
```ts
import express from 'express'
import { query } from 'express-validator'
const app = express()

const getCertificateValidation = [
  query('data')
    .not()
    .isEmpty()
    .trim()
    .isBase64()
    .customSanitizer((value: any) => JSON.parse(Buffer.from(value, 'base64').toString()))
    .isJSON(),
];

const middleware = (req: express.Request, res: express.Response, next: express.NextFunction) => {
  res.sendStatus(200)
}

app.get('/', getCertificateValidation, middleware)

app.listen(3000)
```

**Comment by fedeci** [comment]
Can I assume this has been fixed?

**Comment by moshie** [comment]
@fedeci We ended up going a different route in the end I'll close this issue but the bug might still exist

**Comment by fedeci** [comment]
Can you please provide an example repo so that I can eventually fix it?

**Comment by moshie** [comment]
Will do can't say I'll get to it today but sometime this week.

**Comment by fedeci** [comment]
Thanks!

**Comment by JimmyBjorklund** [comment]
app/server.ts:53:8 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'NextHandleFunction' is not assignable to parameter of type 'PathParams'.
      Type 'NextHandleFunction' is not assignable to type '(string | RegExp)[]'.

53   .use(express.json())


const app = express();
app
  .set("port", port)
  .set("trust proxy", 2)
  .disable("x-powered-by")
  .use(requireHttps())
  .use(i18n.init)
  .use(express.json())

**Comment by ravigill3969** [comment]
i am facing same thing rn.
